lib/controllers/boxesController.js, lib/decoding/transformAndValidateArray.js, lib/models/box.js, lib/models/integrations.js, lib/mqtt/index.js, lib/utils.js, tests/data/getUserBoxesSchema.js, tests/tests.js
Adds the property `integrations: { mqtt, ttn }` to `box`.
- the schema for `integrations.ttn` is:
```js
{
// as registered in thethingsnetwork 
app_id: String,
dev_id: String,
// json: data comes in `payload` as JSON in the API's currently consumable JSON schema
// bytes: data comes in `payload_raw` as byte string, which gets decoded according to a profile
messageFormat: Enum['json', 'bytes'],
decodeOptions: {
// custom: bytes get decoded through a custom byte mask specified in byteMask
// sensebox/home: the currently only predefined configuration as implemented in
//                lora/ttnPayloadFunctionExample.js
profile: Enum['custom', 'sensebox/home'],
// defines the amount of bytes to consume for each sensor. each element matches one sensor in `box.sensors` in the same order …
```
=> store TTN configuration for each box

files/template_home_wifi_feinstaub/template_home_wifi_feinstaub.ino
see #88. I checked, only the WiFi sketch is affected.
We should think about swapping these sensorIds of boxes that were already registered with this sketch.
(untested) migration:
```js
var boxIter = db.boxes.find({
model: 'homeWifiFeinstaub',
createdAt: { $lt: ISODate('2017-06-10T19:13:04.319Z') } // change to time when fix goes live
});
var boxesBulk = db.boxes.initializeUnorderedBulkOp();
// swap sensorIds for PM10 and PM2.5 sensors
while (boxIter.hasNext()) {
var box = boxIter.next();
var pm10ID = box.sensors[5]._id, // old sketch sends pm25 to this
pm25ID = box.sensors[6]._id; // old sketch sends pm10 to this
boxesBulk.update(
{ _id: box._id },
{ $set: { 'sensors.5._id': pm25ID, 'sensors.6._id': pm10ID } }
);
}
boxesBulk.execute();
```
=> swap pm10 and pm2.5 (fixes #88)

lib/controllers/boxesController.js, lib/decoding/csvHandler.js, lib/decoding/validators.js, lib/models/box.js, lib/utils.js, tests/tests/002-location_tests.js
- fixes 2 bugs
- changes behavior for location updates at measurement insertion, to simplify the function
- the rare (?) use case is not supported anymore, where *some* measurements provide a location, while others don't AND when they are sent unordered by time. details in commit message
- adds location fields to csv measurement handler
- adds a time filter to /boxes/:boxId/locations
=> Mobile followup

CHANGELOG.md, packages/api/package.json, packages/models/CHANGELOG.md, packages/models/package.json
Support the new device registration concept (see https://github.com/sensebox/ttn-osem-integration/issues/8) once https://github.com/sensebox/ttn-osem-integration/pull/13 is merged.
=> support new ttn-integration

CHANGELOG.md, packages/api/package.json, packages/models/CHANGELOG.md, packages/models/package.json, packages/models/src/box/box.js
`Custom` senseBox models are marked as `old` though they have live data.
The box property `lastMeasurementAt` is also set on uploading a single measurement for a sensor.
This is a fix for #177
=> Set lastMeasurementAt on single measurement upload

CHANGELOG.md, packages/api/lib/controllers/boxesController.js, packages/api/package.json, packages/models/CHANGELOG.md, packages/models/package.json, packages/models/src/box/box.js, packages/models/src/user/mails.js, yarn.lock
The latest beta release of `@sensebox/sketch-templater` adds variables and replacements for `ssid` and `password` for senseBox MCU WiFi models.
You can post `ssid` and `password` for your wifi to the `/script` route and it will replace it inside the arduino sketch.
Now it is possible to get a full configured sketch which can be used in combination with the `compiler` used by `ardublockly for senseBox` to get a `.bin` file. This file can be copied to the new senseBox MCU in USB mode. Finally you need no installed Arduino on your computer.
=> Possibility to send WiFi credentials for sketch

packages/api/lib/controllers/measurementsController.js
Added Lines to discribe the obligatory use of the Timestamp when posting with a Location
This Fix solves a missunderstanding in the Docs, to help with better use of the API
This has been tested via the API itself.
=> Fixed Docs missunderstanding

packages/api/lib/controllers/measurementsController.js, packages/api/lib/helpers/userParamHelpers.js, packages/api/lib/routes.js, tests/data/boxSensorsSchema.js, tests/data/sensorSchema.js, tests/tests/007-download-data-test.js
This PR adds a new route for retrieving the latest measurement of a single sensor.
Example:
```
GET /boxes/:boxId/sensors/:sensorId
{"title":"UV-Intensität","unit":"μW/cm²","sensorType":"VEML6070","icon":"osem-brightness","_id":"5f3d7e319b0b56c8bff36547","lastMeasurement":{"value":"4","createdAt":"2020-08-19T19:33:29.395Z"}}
```
=> Add route for retrieving the latest measurement of a single sensor

packages/api/lib/controllers/measurementsController.js, tests/tests/007-download-data-test.js
=> fix download in getData closes #325 (#349)

.github/workflows/deploy-docs.yaml, .github/workflows/test.yaml, CONTRIBUTING.md, README.md
This PR removes all mentions of the `development` branch. From now on, `master` is the development branch.
=> remove mentions of development branch

.github/dependabot.yml, CONTRIBUTING.md, Dockerfile, README.md, packages/api/package.json, tests/tests-Dockerfile, yarn.lock
This PR bumps the used node version to 14. Package `apicache` added a `node < 13` in `1.5.3`. Thus the downgrade.
=> Use node v14

.github/workflows/test.yaml, packages/api/lib/controllers/boxesController.js, packages/models/package.json, packages/models/src/box/box.js, yarn.lock
Adding another parameter to the getSketch() function, which enables display usage. 
Relevant PR can be found: 
-  [node-sketch templater ](https://github.com/sensebox/node-sketch-templater/pull/40)
- [OSM i18n](https://github.com/sensebox/openSenseMap-i18n/pull/48)
- https://github.com/sensebox/openSenseMap/pull/394
=> Added display to getSketch()

packages/api/lib/controllers/boxesController.js
This PR adds the missing docs change for #410 and changes all the other parameters of the sketch endpoint in the docs to optional.
@felixerdy seems you were the one implementing all the other parameters. is it correct that these should be marked as optional for the request?
=> Add display_enabled param to docs

packages/api/package.json
PR to manually unpin apicache package. The maintainer recently released a version compatible with node 14
=> Unpin apicache package

packages/api/lib/controllers/boxesController.js, packages/models/src/box/box.js, tests/tests/005-create-boxes-test.js
This PR introduces two new parameters for `/boxes` to query and filter boxes by name. It should be used
to search for boxes in the frontend.
Right now the search for boxes in implemented in the frontend. This should be moved to the backend.
Tested it locally and wrote some tests
=> (api) add parameters to search for boxes with a name

packages/models/src/measurement/decoding/luftdatenHandler.js
Extend `luftdaten.info` (sensor.community) handler and add new sensor matchings.
The `sensor.community` sketch was extended and new sensors were added. The sensor matching was extended with the new sensors.
With this changes `sensor.community` devices can be created as manual devices during registration process on openSenseMap. The user must create the sensors according to the matching mechanism within the openSenseMap API.
The mechanism is matching the sensor type and sensor title according to the `sensor.community` sketch payload.
A blog post will be published shortly after merging and deployment to production.
=> Luftdaten handler and sensor matchings

packages/api/lib/controllers/managementController.js
Change parameter `grouptag` to `['String']` within the management routes.
The `grouptag` in the `box` schema changed from `String` to `['String']` (array of strings). 
We forgot to update the parameter inside our management routes that are used by our admin tool.
=> Update grouptag in management routes

CONTRIBUTING.md, packages/api/lib/controllers/boxesController.js, packages/api/lib/helpers/userParamHelpers.js, packages/models/src/box/box.js, tests/tests/002-location_tests.js
`near` parameter in `getBoxes` is now validated properly. Values passed must be of type `Number` because it represents coordinates.
Parameter is not validated and was throwing errors by providing wrong values like `String`.
Added test with wrong parameters.
=> Validate near parameter

docker-compose.yml, packages/api/lib/controllers/usersController.js, packages/models/index.js, packages/models/package.json, packages/models/src/user/mails.js, packages/models/src/user/user.js, tests/docker-compose.yml, tests/redis/local-redis-stack.conf, tests/tests.js, tests/tests/ZZZ-mail-test.js, yarn.lock
This PR removes the old `mailer` configuration and deprecated the old [mailer](https://github.com/sensebox/sensebox-mailer). We are having some trouble with the mailer written in `go` and I have no idea how to fix the issues.
I have no idea how the old mailer in go works. So I have decided to deprecate the old mailer and implement a new one written in Typescript and based on BullMQ (Redis based queue system). The new mailer is available [here](https://github.com/openSenseMap/mailer).
The queue system could also be used in other scenarios. The old mailer (go) is still configurable but is deprecated from now on.
Check out the updated tests and `docker-compose.yml` setup within the `tests` folder
=> Remove old mailer and add Redis based queue system

packages/models/package.json, yarn.lock
Compiling senseBox sketches is failing with a 500 error. This is based on a wrong EOL encoding in the `sketch-templater` version 1.13.0.
Version 1.13.1 changed the way of handling EOL in arduino templates.
=> Update Sketch Templater

.scripts/run-tests.sh, packages/api/lib/controllers/usersController.js, packages/api/lib/routes.js, packages/models/src/user/user.js, tests/data/getUserBoxSchema.js, tests/tests/005-create-boxes-test.js
This PR adds a simple pagination functionality to the `/users/me/boxes` endpoint and introduces a new endpoint at `/users/me/boxes/:boxId` to retrieve a specific box of a logged in user.
Right now the API performs pretty slow on this request if the users has more than 100 boxes in his account. All boxes are populated and that takes time. Therefore a new parameter `page` is introduced and the result is limited to 25 boxes. To paginate through all included boxes increase the `page` parameter to get the next results.
Test have been added to the testsuite.
=> Simple pagination for embedded boxes on user object

packages/models/index.js, packages/models/src/user/user.js
=> (feat): add configuration for pagination and remove population for lastMeasurement

packages/api/lib/helpers/userParamHelpers.js
We have specified `latitude` and `longitude` order in different ways in our documentation. This PR unifies the order to `lng,lat,height`.
Closes #360
=> (docs): clarify longitude and latitude order

packages/models/src/user/user.js, tests/tests/004-users-test.js
The API returned a wrong response when updating a user with no changed values.
Closes #778 
One test case was added.
=> Return correct response if user was not updated

packages/models/package.json, packages/models/src/box/box.js, packages/models/src/box/integrations.js, packages/models/src/db.js, packages/models/test/tests/0-user.js, yarn.lock
Finally update used `mongoose` dependency.
=> Update mongoose to latest v5

config/config.example.json, config/default.js, packages/api/lib/controllers/usersController.js, packages/api/lib/helpers/badgrQuery.js, packages/api/lib/routes.js, packages/models/src/user/integrations.js, packages/models/src/user/user.js
This PR introduces user integrations. `integrations` is a sub-document on the `user` schema.
The first user integration is [myBadges](https://mybadges.org).
With the integration of *myBadges* it is possible to earn different Badges and adds a gamification aspect to the openSenseMap API.
The API is only forwarding some kind of requests to [Honeybadgr](https://github.com/openSenseMap/honeybadgr/) that is handling the granting process of a badge.
Users who want to participate and earn badges must sign up on https://mybadges.org with the same email address as their openSenseMap user.
=> feat(user): add myBadges integration

config/default.js, packages/api/app.js, packages/api/lib/controllers/usersController.js, packages/api/logger.js, packages/api/package.json, yarn.lock
This PR introduces different kind of logger. Right now the API has one logger and its the default one provided by `restify` and uses `pino` under the hode.
This hat a motivational background in debugging purposes and support requests. Right now it is only possible to see some basic information in requests coming in and sometimes it is quite hard to identify the issue.
The introduced `debugLogger` extends the log message by including the request `body`. It should only be used in support cases.
=> chore: add logger for debugging purposes
