migrations/mongoshell-20170125-mobileboxes.js
migrations/mongoshell-20170302-ttn.js
run-migrations.sh

fixes #71
run all migrations with ./run-migrations.sh

add migration scripts for TTN integration

---

lib/controllers/boxesController.js
lib/models/box.js
lib/models/integrations.js
migrations/mongoshell-20170302-ttn.js
tests/data/getUserBoxesSchema.js
tests/tests.js

- no more messageFormat (will be inferred from payload format)
- move `decodeOptions.profile` -> `profile`
- move `decodeOptions.bytemask` -> `decodeOptions`

simplify TTN config schema

---

lib/controllers/boxesController.js
lib/models/box.js
lib/models/user.js
lib/requestUtils.js
lib/sensorLayouts/index.js
migrations/3-4_normalize_boxes/3-mongoshell-normalize-boxes.js
tests/data/custom_valid_sensebox.js
tests/tests.js

merge Development to master

---

.eslintrc.js
CHANGELOG.md
package.json
packages/api/lib/controllers/measurementsController.js
packages/api/lib/controllers/statisticsController.js
packages/api/lib/helpers/apiUtils.js
packages/api/lib/routes.js
packages/api/lib/transformers/descriptiveStatisticsTransformer.js
packages/api/package.json
packages/models/src/box/box.js
tests/tests/007-download-data-test.js
tests/tests/013-classify-test.js
tests/tests/014-descriptive-statistics-test.js
yarn.lock

Compute means

---

.scripts/create-version.js
.travis.yml
CHANGELOG.md
packages/api/app.js
packages/api/lib/controllers/statisticsController.js
packages/api/lib/transformers/classifyTransformer.js
packages/models/.npmignore
packages/models/CHANGELOG.md

Pull request to merge changes for version api v3 and models v0.0.8 into master
- Fix travis docs build
- Fix version.js creation script
- Update npmignore
- Slight classifyTransformer refactor to avoid multiple moment calls

Merge changes for v3

---

.dockerignore
.npmignore
.scripts/deploy-docs.sh
.scripts/run-tests.sh
.travis.yml
apidoc.json
apidoc/introduction.md
package.json

This pull request updates the travis ci build to include running the testing suite.
It also changes the docs. They now include an introduction section explaining timestamps and ids. Also fixes #144 
Changes for changelog
- Explain timestamps and IDs in api docs

Update Travis CI build

---

packages/api/lib/controllers/boxesController.js
packages/api/lib/helpers/apiUtils.js
packages/models/src/user/user.js
packages/models/test/tests/0-user.js

Add more details to slack notification

Slack notification

---

tests/tests/005-create-boxes-test.js

add tests for checking empty sensors

---

packages/api/lib/controllers/boxesController.js

This pull request extends the documentation and fixes #167

document box/sensor updating, fixes #167

---

packages/api/lib/controllers/boxesController.js
packages/models/package.json
packages/models/src/box/sensorLayouts/index.js
yarn.lock

Add new model for automatically generating a Arduino sketch with LoRa setup for ttn.

Add new LoRa model

---

packages/api/lib/controllers/measurementsController.js
packages/api/lib/transformers/classifyTransformer.js
packages/models/migrations/5-7_measurements_boxes/5-mongoshell-boxes-add-field.js
packages/models/migrations/5-7_measurements_boxes/6-node-set-latest-measurement.js
packages/models/src/box/box.js
packages/models/test/tests/1-box.js
tests/data/findAllSchemaBoxes.js
tests/tests/002-location_tests.js
tests/tests/006-submit-measurements-test.js
tests/tests/007-download-data-test.js

Adds new field with lastMeasurements timestamp to box model.

Performance of initial /boxes request

---

packages/api/lib/controllers/boxesController.js
packages/models/package.json
packages/models/src/box/box.js

This PR adds the option to include a digital port for the soil moisture sensor (smt50) and sound level meter
I extended the `getSketch` method and added necessary parameters. 
tests worked

Newsensors

---

packages/models/src/box/sensorLayouts/sensorDefinitions/bme680_humidity.js
packages/models/src/box/sensorLayouts/sensorDefinitions/bme680_pressure.js
packages/models/src/box/sensorLayouts/sensorDefinitions/bme680_temperature.js

match sensor titles with sensor ids from sketch-templater

---

packages/models/package.json

bump node-sketch-templater version

---

packages/api/package.json
packages/models/CHANGELOG.md
packages/models/package.json

Bump models version

---

packages/api/package.json

bump opensensemap-api-models version

---

yarn.lock

Merge master in development

---

packages/api/lib/helpers/userParamHelpers.js
yarn.lock

Resolve conflicts

---

README.md
packages/api/lib/controllers/boxesController.js
packages/models/src/box/integrations.js

Adding Cayenne LPP Decoding Profile. Works with https://github.com/sensebox/ttn-osem-integration/tree/cayenne

Cayenne LPP Decoding Profile

---

packages/api/lib/controllers/measurementsController.js
tests/tests/007-download-data-test.js

fix download in getData closes #325

---

.dependabot/config.yml
.github/dependabot.yml

Bumps dependabot config from v1 to v2 (github native)

Update dependabot config to v2

---

packages/api/package.json
packages/models/CHANGELOG.md
packages/models/package.json
yarn.lock

New light sensor in sketch templater

New light sensor

---

packages/api/package.json
packages/models/CHANGELOG.md
packages/models/package.json
yarn.lock

Power UART in setup

---

Dockerfile
docker-compose.yml
tests/docker-compose.yml
tests/tests-Dockerfile

Update used docker images and fix python installation

---

docker-compose.yml

Switch to multi-arch mongo development image for openSenseMap
Local development set up is not running on new Mac M1 based architectures.
Tested on my own machine.

Switch to multi-arch mongo image

---

.github/workflows/registry-purge-pr.yaml

Remove dry-run option for deleting PR images

---

.github/workflows/test.yaml

Remove docker hub login

---

.github/workflows/registry.yaml

Use PAT in order to delete untagged images

---

packages/api/lib/controllers/boxesController.js
packages/models/src/box/sensorLayouts/sensebox.home.mcu.js
packages/models/src/box/sensorLayouts/sensorDefinitions/dps310_pressure.js
packages/models/src/box/sensorLayouts/sensorDefinitions/dps310_temperature.js
packages/models/src/box/sensorLayouts/sensorDefinitions/index.js

We offer a new sensor for pressure and temperature measurements called [DPS310](https://sensebox.kaufen/product/dps310).
The `DPS310` sensor also replaces the `BMP280` which is no longer produced. Therefore we need the sensor in the API that it can be registered.

Add new sensorLayout for DPS310

---

docker-compose.yml
images/mongodb/Dockerfile
images/mongodb/README.md
images/mongodb/osem_admin.sh

The mongodb for development purpose had it´s own repository. This PR will move it to this repo
and hopefully simplifies the development set up.

Move osem mongo dev image to api repo

---

config/config.example.json
config/default.js
packages/api/app.js
packages/api/lib/controllers/boxesController.js
packages/api/lib/controllers/managementController.js
packages/api/lib/controllers/usersController.js
packages/api/lib/helpers/apiUtils.js
packages/api/lib/helpers/escapeMarkdown.js

We don´t use Slack anymore. So this PR adds a function to send all notifications to mattermost instead.

Replace slack notifications with mattermost

---

packages/api/lib/controllers/managementController.js
tests/tests/015-admin-test.js

This PR changes the queries to get `boxes` and `users` via the `management` routes. It removes unnecessary attributes and uses `.cursor`.
The `management` routes to handle administrative tasks are not that performant. To make our admin tool usable again these changes are needed
Admin tests were updated to reflect the changes.

Update management routes for admin users.

---

.dockerignore
Dockerfile
packages/api/app.js
packages/api/lib/routes.js
packages/api/package.json
packages/models/package.json
tests/tests-Dockerfile
tests/tests/004-users-test.js
yarn.lock

Upgrade bcrypt to use node v16

---

packages/models/src/box/box.js
packages/models/src/measurement/decoding/luftdatenHandler.js

Fix broken sensors with undefined values

---

packages/models/src/box/box.js

Check if id is undefined

---

README.md

Update Readme to include correct used versions.

Update Readme closes #700

---

packages/api/lib/controllers/measurementsController.js

Documented route `/boxes/data/bytag` correctly and added missing parameters.
Closes #706

(docs): document getDataByTag correctly

---

packages/api/lib/controllers/boxesController.js
packages/api/lib/controllers/measurementsController.js
packages/api/lib/controllers/sensorsController.js

Add return values and response examples to `/boxes` route documentation
Will be adding more over the time
Closes #782

better return types documentation

---

packages/api/lib/controllers/boxesController.js
packages/models/src/box/box.js

This PR adds the possibility to pass a detailed description for a new senseBox during the registrataion process.
Closes #729

(feat): add description to `postNewBox` route

---

.github/PULL_REQUEST_TEMPLATE.md
packages/models/package.json
yarn.lock

(chore): update grpc dependencies

---

package.json
yarn.lock

Update mocha dependency

---

package.json
yarn.lock

Update mqtt dependency

---

package.json
yarn.lock

Update chai dependencies

---

.github/workflows/deploy-docs.yaml
.github/workflows/registry-purge-pr.yaml
.github/workflows/registry-purge.yaml
.github/workflows/registry.yaml
.github/workflows/test.yaml

Some updates to our Github Action workflows

(chore): update actions and use correct node version

---

.scripts/run-tests.sh
packages/models/src/box/sensorLayouts/sensorDefinitions/dnms_la_eq.js
packages/models/src/box/sensorLayouts/sensorDefinitions/dnms_la_max.js
packages/models/src/box/sensorLayouts/sensorDefinitions/dnms_la_min.js
packages/models/src/box/sensorLayouts/sensorDefinitions/index.js
packages/models/src/measurement/decoding/luftdatenHandler.js
tests/tests/ZZZ-mail-test.js

feat: add DNMS sensor and handle it in luftdaten handler

---

packages/api/lib/controllers/measurementsController.js

only a typo
no typos are better than some typos
no testing needed
typo

fix typo: `measruement` ➡ `measurement`
